CREATE OR REPLACE VIEW V_DESIGNER_MENU
 AS
  SELECT A.MENU_NAME,
         C.DSI_NAME,
         C.DSI_POSI,
         B.PRICE
    FROM MENU A, MENU_PRICE B, DESIGNER C
   WHERE A.MENU_NO = B.MENU_NO
     AND B.DSI_NO = C.DSI_NO
   ORDER BY 1
   WITH READ ONLY;


SELECT MENU_NAME,DSI_NAME,DSI_POSI,PRICE
 FROM V_DESIGNER_MENU
 WHERE DSI_NAME = '김실장';
 

   
